from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

Rating = Literal["strong", "medium", "none"]


class SearchResult(BaseModel):
    query: str
    title: str
    link: str
    snippet: str
    date: str | None = None


class DocsPage(BaseModel):
    url: str
    title: str
    content: str
    fetched_at: datetime = Field(default_factory=datetime.now)


class FeedEntry(BaseModel):
    source: str  # "github" or "pypi"
    title: str
    link: str
    published: str | None = None
    summary: str = ""


class CompetitorData(BaseModel):
    competitor_name: str
    search_results: list[SearchResult] = []
    category_search_results: dict[str, list[SearchResult]] = {}
    docs_pages: list[DocsPage] = []
    feed_entries: list[FeedEntry] = []


class CollectionRun(BaseModel):
    date: str
    mode: str = "initial"  # "initial" or "update"
    competitors: list[CompetitorData] = []
    weave_data: CompetitorData | None = None


class FeatureRating(BaseModel):
    item_name: str          # Must match config sub-item exactly
    rating: Rating
    note: str = ""


class CategoryAnalysis(BaseModel):
    category_name: str      # Must match CategoryDef.name
    features: list[FeatureRating]
    summary: str


class NewFeature(BaseModel):
    feature_name: str
    description: str
    release_date: str
    category: str


class PositioningShift(BaseModel):
    current_position: str
    moving_toward: str
    signal: str


class CompetitorAnalysis(BaseModel):
    competitor_name: str
    overall_summary: str
    categories: list[CategoryAnalysis]  # 7 categories
    new_features: list[NewFeature] = []
    positioning: PositioningShift
    strengths: list[str]
    weaknesses: list[str]


class ProductSummaryRating(BaseModel):
    product_name: str
    trace_depth: Rating
    trace_depth_note: str = ""
    eval: Rating
    eval_note: str = ""
    agent_observability: Rating
    agent_observability_note: str = ""
    cost_tracking: Rating
    cost_tracking_note: str = ""
    enterprise_ready: Rating
    enterprise_ready_note: str = ""
    overall: Rating
    overall_note: str = ""


class SynthesisResult(BaseModel):
    executive_summary: list[str] = []   # Generated by dedicated LLM call
    market_insights: list[str] = []     # 3 analytical insights (generated by dedicated LLM call)
    market_summary: str = ""            # Overall market landscape
    product_ratings: list[ProductSummaryRating] = []
    enterprise_signals: list[str] = []


class AnalysisRun(BaseModel):
    date: str
    model: str
    collection_date: str
    competitors: list[CompetitorAnalysis] = []
    synthesis: SynthesisResult | None = None


class EmergingCompetitor(BaseModel):
    name: str
    description: str
    source_url: str


class DiscoveryResult(BaseModel):
    date: str
    queries: list[str] = []
    search_results_count: int = 0
    emerging_competitors: list[EmergingCompetitor] = []
